server:
    port: 5001

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/yt_task_user_service
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true  # Uncomment this line if you want to show SQL in the logs
